#!/bin/bash

npm run db:mig:deploy

ENV_FILE=".env"

cat <<EOL > $ENV_FILE
PORT=$PORT
PG_DB_URL=$PG_DB_URL
AWS_S3_KEY=$AWS_S3_KEY
AWS_S3_SECRET=$AWS_S3_SECRET
AWS_SES_KEY=$AWS_SES_KEY
AWS_SES_SECRET=$AWS_SES_SECRET
PUBLIC_BUCKET_NAME=$PUBLIC_BUCKET_NAME
PRIVATE_BUCKET_NAME=$PRIVATE_BUCKET_NAME
NODE_ENV=$NODE_ENV
JWT_SIGNING_KEY_SECRET=$JWT_SIGNING_KEY_SECRET
PUBLIC_BUCKET_NAME=$PUBLIC_BUCKET_NAME
PRIVATE_BUCKET_NAME=$PRIVATE_BUCKET_NAME
GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
LINKEDIN_CLIENT_ID=$LINKEDIN_CLIENT_ID
LINKEDIN_CLIENT_SECRET=$LINKEDIN_CLIENT_SECRET
REDIRECT_URL=$REDIRECT_URL
EOL

echo ".env file created with environment variables."

npm start