module.exports = {
	displayName: 'Gamix Tests',
  testMatch: ['<rootDir>/src/**/*.spec.ts'],
	preset: 'ts-jest',
	testEnvironment: 'node',
	roots: ['<rootDir>/src'],
	moduleNameMapper: {
		'^@/(.*)$': '<rootDir>/src/$1',
		'^@config/(.*)$': '<rootDir>/src/config/$1',
		'^@shared/(.*)$': '<rootDir>/src/shared/$1',
		'^@features/(.*)$': '<rootDir>/src/features/$1',
		'^@test/(.*)$': '<rootDir>/src/test/$1',
		'^@tsoa-build/(.*)$': '<rootDir>/src/tsoa/$1',
		'^@ioc$': '<rootDir>/src/config/ioc.ts'
	},
	setupFilesAfterEnv: ['<rootDir>/src/test/jest.setup.ts'],
	collectCoverageFrom: [
		'src/**/*.ts',
		'!src/**/*.spec.ts',
		'!src/test/**/*.ts',
		'!src/tsoa/**/*.ts',
		'!src/index.ts',
		'!src/config/processWatcher.ts',
		'!src/utils/startup-manager.ts',
		'!src/utils/route-lister.ts',
		'!src/utils/logger.ts',
		'!src/shared/types/*.ts',
		'!src/config/ioc.ts',
		'!src/config/app.ts',
	],
	coverageDirectory: 'coverage',
	testTimeout: 30000,
	maxWorkers: 1,
	verbose: true,
	forceExit: true,
	detectOpenHandles: true
}
